using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using api.Interfaces; // add this manually if shortcut does not work
using api.Models; // add this manually if shortcut does not work
using Microsoft.EntityFrameworkCore; // add this manually
using api.Data; // add this manually

namespace api.Repository
{
    public class StockRepository : IStockRepository // the child code (the iterface here) was automatically generated by hovering on the 'IStockRepository' and pressing ctrl + . If not working, you need to manually supply the interface here, like the code below. Do not forget to add the using api.Interfaces; using api.Models;
    {
        // BOILERPLATE : add this manually if shortcut does not work
        // public Task<List<Stock>> GetAllAsync()
        // {
            
        // }

        private readonly ApplicationDBContext _context;

        // THIS IS DEPENDENCY INJECTION - constructor injection
        public StockRepository(ApplicationDBContext context){
            _context = context;
        }

        public Task<List<Stock>> GetAllAsync()
        {
            return _context.Stocks.ToListAsync();
        }

    }
}